services:
  backend:
    build: ./book_notes_backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL="postgresql://book_app_user:passtest12345@localhost/book_notes"
    volumes:
      - ./book_notes_backend/app:/app

  frontend:
    build: ./book_notes_frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
      - ./book_notes_backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
